SELECT C.*, L.NAME, CN.NAME
FROM TRIP T INNER JOIN ARRIVAL A on T.ID = A.TRIPID INNER JOIN CARGO_MANIFEST CM on CM.ARRIVALID = A.ID INNER JOIN TYPE_CARGO_MANIFEST TCM on TCM.ID = CM.TYPE_CARGO_MANIFESTID
            INNER JOIN CONTAINER_CARGO_MANIFEST CCM on CM.ID = CCM.CARGO_MANIFESTID INNER JOIN CONTAINER C on CCM.CONTAINERID = C.ID
            INNER JOIN LOCATION L on L.ID = A.DESTINATIONLOCATIONID
            INNER JOIN COUNTRY CN ON CN.ID = L.COUNTRYID
            INNER JOIN Vehicle v ON v.id = t.vehicleid
        INNER JOIN Ship s ON v.id = s.vehicleid
WHERE S.MMSI = 211331643 AND A.DESTINATIONLOCATIONID = 7 AND TCM.DESIGNATION = 'loading'
ORDER BY A.ARRIVAL_DATE ASC;